name: Tests

on: [push, pull_request]

jobs:

  test-module:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - uses: actions/checkout@v1
      with:
        repository: biigle/core
        ref: dev-modules
        fetch-depth: 1
        path: core

    - name: Validate composer.json and composer.lock
      run: composer validate
      working-directory: ../core

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      working-directory: ../core

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer
        restore-keys: |
          ${{ runner.os }}-composer

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --prefer-dist --ignore-platform-reqs
      working-directory: ../core

    - name: Remove BIIGLE modules
      run: rm -r vendor/biigle
      working-directory: ../core

    - name: Update BIIGLE modules from source
      run: composer update --no-ansi --no-interaction --no-scripts --no-suggest --prefer-source --ignore-platform-reqs biigle/*
      working-directory: ../core

    - name: Remove installed package
      run: rm -r vendor/${GITHUB_REPOSITORY}
      working-directory: ../core

    - name: Copy current repository
      run: cp -r ${GITHUB_WORKSPACE} vendor/biigle
      working-directory: ../core

    - name: Generate key
      run: php artisan key:generate
      working-directory: ../core

    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Fetch base images
      run: |
        docker pull docker.pkg.github.com/biigle/core/app:latest
        docker pull docker.pkg.github.com/biigle/core/worker:latest

    - name: Start test database
      run: docker-compose up -d --no-build database_testing
      working-directory: ../core

    - name: Run tests
      run: docker-compose run --rm -u 1001 worker php -d memory_limit=1G vendor/bin/phpunit --random-order --filter 'Biigle\\Tests\\Modules\\'${GITHUB_REPOSITORY##*/}
      working-directory: ../core
